from pathlib import Path
import struct,shutil
import wd19_common as c
B=Path(Path('wd113_path.txt').read_text(encoding='utf8').strip());P=Path(Path('wd114_path.txt').read_text(encoding='utf8').strip())
def pack(rows,pool):
 f=len(next(iter(rows.values())));return struct.pack('<4s4I',b'WDBC',len(rows),f,f*4,len(pool))+b''.join(struct.pack('<'+'I'*f,*r)for r in rows.values())+pool
for prefix in ['03_覆盖到服务端根目录/Data/dbc','client_mpq输入_导入现有Patch-XA/DBFilesClient']:
 rows,pool=c.dbc((B/prefix/'Spell.dbc').read_bytes())
 for id in [9003853,9003854]:assert id not in rows
 # Native Feign Death supplies target flags, interrupt behavior and supported visual.
 r=rows[5384].copy();r[0]=9003853;r[38]=r[39]=10;r[40]=5;r[208:212]=[0]*4
 # Five minutes from the official donor, 30 sec cooldown; no cost or reagent.
 r[29]=30000;r[30]=0;r[1]=0;r[133]=rows[9003850][133]
 # Spell book visible; preserve the native feign-death interrupt/stance flags.
 r[4]&=~(0x40|0x80|0x02000000);rows[r[0]]=r # donor cooldown starts on cast, not aura expiry
 r=rows[9003850].copy();r[0]=9003854;r[133]=rows[9003101][133]
 r[95]=136;r[110]=127;r[80]=3 # +4% healing
 r[96]=108;r[111]=2;r[81]=(-16)&0xffffffff # -15% spell threat, not Aura103 flat threat
 rows[r[0]]=r
 texts={9003853:("假死药剂 / Death Draught","喝下药剂进入假死，最多持续5分钟。30秒冷却。移动或主动取消后恢复；不是免疫，副本中可能仍处于战斗。 / Feign death for up to 5 min. 30 sec cooldown. Move or cancel to stand. Not immunity; dungeon combat may persist."),9003854:("强效混合 / Potent Mixes","治疗量提高4%，法术产生的威胁降低15%。不减少已有仇恨或普通近战白字仇恨。 / Healing done +4%; threat generated by spells -15%. Does not erase existing threat or reduce white melee threat.")}
 for sid,(name,desc) in texts.items():
  for start,value in [(136,name),(153,''),(170,desc),(187,desc if sid==9003853 else '')]:
   offset=len(pool);pool+=value.encode()+b'\0';rows[sid][start:start+16]=[offset]*16
 target=P/prefix/'Spell.dbc';target.write_bytes(pack(rows,pool))
 rows,pool=c.dbc((B/prefix/'SkillLineAbility.dbc').read_bytes())
 for sid in [9003853,9003854]:
  assert not any(r[2]==sid for r in rows.values())
  r=next(r for r in rows.values()if r[2]==9003640).copy();r[0]=max(rows)+1;r[2]=sid;rows[r[0]]=r
 (P/prefix/'SkillLineAbility.dbc').write_bytes(pack(rows,pool))
 for name in ['Spell.dbc','SkillLineAbility.dbc']:
  d=P/'rollback_WD113'/prefix/name;d.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(B/prefix/name,d)
rel=Path('02_覆盖到客户端根目录/Interface/AddOns/RebornWitchDoctorTalents')
live=c.R/'beascendclient/newrebornWOWli20260929beAscend/Interface/AddOns/RebornWitchDoctorTalents/RebornWitchDoctorTalents.toc'
toc=live.read_text(encoding='utf-8-sig')
backup=P/'rollback_WD113'/rel/live.name;backup.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(live,backup)
(P/rel/live.name).write_text(toc+'\nNumericTooltip.lua\n',encoding='utf8')
shutil.copy2('wd114_numeric.lua',P/rel/'NumericTooltip.lua')
print('Separate DBCs and server-backed tooltip prepared')
