-- Custom glyphs defined via the client patch pipeline.
-- GENERATED by tools/build_client_patch.py from tools/client_patch_manifest.json
-- (client side: wow-client/Data/patch-P.mpq). Do not edit by hand.

DELETE FROM `glyphproperties_dbc` WHERE `ID` IN (1501, 1502, 1503, 1504, 1505);
INSERT INTO `glyphproperties_dbc` (`ID`, `SpellID`, `GlyphSlotFlags`, `SpellIconID`) VALUES
    (1501, 200101, 1, 3125),
    (1502, 200102, 0, 3128),
    (1503, 200103, 1, 3110),
    (1504, 200104, 1, 3117),
    (1505, 200105, 1, 3110);

DELETE FROM `spell_dbc` WHERE `ID` IN (200001, 200101, 200002, 200102, 200003, 200103, 200004, 200104, 200005, 200105);
INSERT INTO `spell_dbc`
    (`ID`, `Attributes`, `AttributesEx`, `Targets`, `InterruptFlags`, `ProcChance`,
     `CastingTimeIndex`, `DurationIndex`, `RangeIndex`, `EquippedItemClass`,
     `Effect_1`, `ImplicitTargetA_1`, `EffectAura_1`, `EffectMiscValue_1`,
     `SpellVisualID_1`, `SpellIconID`, `SchoolMask`, `Name_Lang_enUS`) VALUES
    (200001, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1501, 12369, 1475, 1, 'Glyph of the Orca'),
    (200101, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 1475, 1, 'Glyph of the Orca'),
    (200002, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1502, 12369, 292, 1, 'Glyph of the Zealot'),
    (200102, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 292, 1, 'Glyph of the Zealot'),
    (200003, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1503, 12369, 107, 1, 'Glyph of the Fel Werebear'),
    (200103, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 107, 1, 'Glyph of the Fel Werebear'),
    (200004, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1504, 12369, 1178, 1, 'Glyph of the Wolf'),
    (200104, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 1178, 1, 'Glyph of the Wolf'),
    (200005, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1505, 12369, 107, 1, 'Glyph of the Grizzlemaw'),
    (200105, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 107, 1, 'Glyph of the Grizzlemaw');

DELETE FROM `item_template` WHERE `entry` IN (100001, 100002, 100003, 100004, 100005);
INSERT INTO `item_template`
    (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `BuyPrice`, `SellPrice`,
     `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `stackable`,
     `bonding`, `description`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `Material`) VALUES
    (100001, 16, 0, 'Glyph of the Orca', 52559, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200001, 0, -1, -1),
    (100002, 16, 0, 'Glyph of the Zealot', 58828, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200002, 0, -1, -1),
    (100003, 16, 0, 'Glyph of the Fel Werebear', 52559, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200003, 0, -1, -1),
    (100004, 16, 0, 'Glyph of the Wolf', 52559, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200004, 0, -1, -1),
    (100005, 16, 0, 'Glyph of the Grizzlemaw', 52559, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200005, 0, -1, -1);

DELETE FROM `custom_glyphs` WHERE `glyph_id` IN (1501, 1502, 1503, 1504, 1505);
INSERT INTO `custom_glyphs` (`glyph_id`, `name`, `handler`, `handler_data`) VALUES
    (1501, 'Glyph of the Orca', 'display', '1066:21975'),
    (1502, 'Glyph of the Zealot', 'proc', 'zealot'),
    (1503, 'Glyph of the Fel Werebear', 'display', '5487,9634:99849'),
    (1504, 'Glyph of the Wolf', 'display', '768:741'),
    (1505, 'Glyph of the Grizzlemaw', 'display', '5487,9634:99852');

-- Add to the shared glyph drop pool
DELETE FROM `reference_loot_template` WHERE `Entry` = 90001 AND `Item` IN (100001, 100002, 100003, 100004, 100005);
INSERT INTO `reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
    (90001, 100001, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Orca'),
    (90001, 100002, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Zealot'),
    (90001, 100003, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Fel Werebear'),
    (90001, 100004, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Wolf'),
    (90001, 100005, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Grizzlemaw');

DELETE FROM `creaturemodeldata_dbc` WHERE `ID` IN (57710, 57711);
INSERT INTO `creaturemodeldata_dbc` (`ID`, `Flags`, `ModelName`, `SizeClass`, `ModelScale`, `BloodID`, `FootprintTextureID`, `FootprintTextureLength`, `FootprintTextureWidth`, `FootprintParticleScale`, `FoleyMaterialID`, `FootstepShakeSize`, `DeathThudShakeSize`, `SoundID`, `CollisionWidth`, `CollisionHeight`, `MountHeight`, `GeoBoxMinX`, `GeoBoxMinY`, `GeoBoxMinZ`, `GeoBoxMaxX`, `GeoBoxMaxY`, `GeoBoxMaxZ`, `WorldEffectScale`, `AttachedEffectScale`, `MissileCollisionRadius`, `MissileCollisionPush`, `MissileCollisionRaise`) VALUES
    (57710, 16, 'Creature\\werebear\\werebear.mdx', 1, 0.5, 1, 7, 18.0, 12.0, 1.0, 0, 0, 0, 3022, 0.6111, 2.031, 0.0, -1.87528, -1.09434, -0.034044, 1.82271, 1.08394, 2.87991, 1.0, 2.5, 0.0, 0.0, 0.0),
    (57711, 16, 'Creature\\druidbear2\\druidbear2_artifact6.mdx', 1, 0.5, 1, 7, 18.0, 12.0, 1.0, 0, 0, 0, 3022, 0.6111, 2.031, 0.0, -1.87528, -1.09434, -0.034044, 1.82271, 1.08394, 2.87991, 1.0, 2.5, 0.0, 0.0, 0.0);

DELETE FROM `creaturedisplayinfo_dbc` WHERE `ID` IN (99849, 99851, 99852, 99853);
INSERT INTO `creaturedisplayinfo_dbc` (`ID`, `ModelID`, `SoundID`, `ExtendedDisplayInfoID`, `CreatureModelScale`, `CreatureModelAlpha`, `TextureVariation_1`, `TextureVariation_2`, `TextureVariation_3`, `PortraitTextureName`, `BloodLevel`, `BloodID`, `NPCSoundID`, `ParticleColorID`, `CreatureGeosetData`, `ObjectEffectPackageID`) VALUES
    (99849, 57710, 0, 0, 1.0, 255, 'werebear_4253131', 'werebear_4253130', 'werebear_4253133', '', -1, 0, 0, 0, 0, 0),
    (99851, 3011, 0, 0, 1.0, 255, 'Harkoa', 'HarkoaGlow', '', '', 0, 0, 0, 0, 0, 0),
    (99852, 57711, 0, 0, 1.0, 255, 'druidbear2_artifact6_brown', '', '', '', -1, 0, 0, 0, 0, 0),
    (99853, 57711, 0, 0, 1.0, 255, 'druidbear2_artifact6_blonde', '', '', '', -1, 0, 0, 0, 0, 0);
