"""
DCAI1A: build the English-name -> creature entry table that lets playerbots' boss tactics find
bosses on a server whose creature_template names were translated (e.g. to Chinese).

Every string literal in mod-playerbots/src that equals (case-insensitively) the English name of a
creature in the upstream AzerothCore creature_template.sql becomes a key; its value is every
upstream entry with exactly that name. Output: a C++ include with one {"name", entry} row each.

usage: python gen_creature_aliases.py <upstream creature_template.sql> <mod-playerbots/src> <out.inc> <report.txt>
"""
import os
import re
import sys
from collections import defaultdict

sql_path, src_dir, out_inc, report = sys.argv[1:5]

# --- upstream names: (entry, difficulty_entry_1..3, KillCredit1..2, 'name', ...)
BS = chr(92)  # backslash, spelled out so no quoting layer can eat it
row = re.compile(r"\((\d+),\d+,\d+,\d+,\d+,\d+,'((?:[^'" + BS + BS + r"]|" + BS + BS + r".|'')*)'")
by_name = defaultdict(set)
text = open(sql_path, encoding="utf-8", errors="replace").read()
for m in row.finditer(text):
    name = m.group(2).replace(BS + "'", "'").replace("''", "'")
    by_name[name.lower()].add(int(m.group(1)))
print(f"upstream creatures: {sum(len(v) for v in by_name.values())} entries, {len(by_name)} names")

# Qualifiers in playerbots that are not a full upstream name (they never matched, even on an
# English server): map them to the creature they clearly mean.
MANUAL = {
    "garfrost": "forgemaster garfrost",  # Ai/Dungeon/PoS/PoSMultipliers.cpp
}
for short, full in MANUAL.items():
    assert full in by_name, full
    by_name[short] |= by_name[full]

# --- literals used in playerbots
lit = re.compile(r'"((?:[^"' + BS + BS + r'\n]|' + BS + BS + r'.)*)"')
used = defaultdict(set)      # lower name -> files
for root, _, files in os.walk(src_dir):
    for f in files:
        if not f.endswith((".cpp", ".h")):
            continue
        p = os.path.join(root, f)
        for s in lit.findall(open(p, encoding="utf-8", errors="replace").read()):
            s = s.replace(BS + "'", "'")
            if len(s) >= 3 and s.lower() in by_name:
                used[s.lower()].add(os.path.relpath(p, src_dir).replace("\\", "/"))

# names only ever used outside Dungeon/Raid/BossAura code are very likely not creature lookups
# (spell / item / command words that happen to equal some creature's name) -- keep them out.
def creature_context(files):
    return any(f.startswith(("Ai/Dungeon/", "Ai/Raid/")) or "BossAura" in f for f in files)

keys = sorted(k for k, files in used.items() if creature_context(files))
skipped = sorted(k for k, files in used.items() if not creature_context(files))

# every "find target" qualifier must be covered, otherwise report it
ft = re.compile(r'"find target",\s*"([^"]*)"')
qualifiers = set()
for root, _, files in os.walk(src_dir):
    for f in files:
        if f.endswith((".cpp", ".h")):
            qualifiers.update(q.lower() for q in ft.findall(open(os.path.join(root, f), encoding="utf-8", errors="replace").read()))
missing = sorted(q for q in qualifiers if q not in by_name)

rows = [(k, e) for k in keys for e in sorted(by_name[k])]
with open(out_inc, "w", encoding="utf-8", newline="\n") as o:
    o.write("// Generated by gen_creature_aliases.py (DCAI1A) from upstream data/sql/base/db_world/creature_template.sql.\n")
    o.write(f"// {len(keys)} English creature names used by playerbots tactics, {len(rows)} entries. Do not edit by hand.\n")
    for k, e in rows:
        o.write('{"%s", %d},\n' % (k.replace("\\", "\\\\").replace('"', '\\"'), e))

with open(report, "w", encoding="utf-8") as r:
    r.write(f"names: {len(keys)}  entries: {len(rows)}\n")
    r.write(f"find target qualifiers: {len(qualifiers)}  not in upstream: {len(missing)}\n")
    for q in missing:
        r.write(f"  MISSING {q}\n")
    r.write(f"\nskipped (only outside Dungeon/Raid code): {len(skipped)}\n")
    for k in skipped:
        r.write(f"  {k}: {', '.join(sorted(used[k]))[:120]}\n")
print(f"names {len(keys)}, entries {len(rows)}, find-target qualifiers {len(qualifiers)}, missing {len(missing)}, skipped {len(skipped)}")
